name: Compile flex

on:
  repository_dispatch:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-22.04 # 使用最新版本的Ubuntu作为运行环境
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive # 确保递归克隆所有子模块

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk ninja-build ccache git-lfs python3-pip
        pip3 install --upgrade meson
        pip3 install --upgrade ninja

    # - name: Setup Repo
    #   run: |
    #     mkdir -p $HOME/bin
    #     curl -Lo $HOME/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
    #     chmod a+x $HOME/bin/repo
    #     echo "$HOME/bin" >> $GITHUB_PATH

    - name: Initialize flexbuild
      run: |
        git clone https://github.com/NXP/flexbuild.git --depth=1

    - name: Build flexbuild
      run: |
        cd flexbuild
        source setup.env
        bld -m ls1043ardb

    - name: Upload artifacts
      if: success() # 只有当编译成功时上传制品
      uses: actions/upload-artifact@v2
      with:
        name: flexbuild-build
        path: build/rfs/*.tar.gz
